version: '3.8'

services:
  db:
    image: mysql:5.7
    restart: unless-stopped
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: MovieDatabase
      MYSQL_USER: mysql
      MYSQL_PASSWORD: root
    ports:
      - '3300:3306'
    volumes:
      - db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db:
